// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAAbcGPhaF7QHRPiOiVlJFrml_0wZ-q4E',
    appId: '1:310271385508:web:961760b700e3e5e4d72b31',
    messagingSenderId: '310271385508',
    projectId: 'expense-tracker-1010',
    authDomain: 'expense-tracker-1010.firebaseapp.com',
    storageBucket: 'expense-tracker-1010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MJxtT_YG-Z3dRZb1M1R5Bo_tHVRjrUg',
    appId: '1:310271385508:android:afd9b47dc1734811d72b31',
    messagingSenderId: '310271385508',
    projectId: 'expense-tracker-1010',
    storageBucket: 'expense-tracker-1010.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAAbcGPhaF7QHRPiOiVlJFrml_0wZ-q4E',
    appId: '1:310271385508:web:48cabc3d429c85ddd72b31',
    messagingSenderId: '310271385508',
    projectId: 'expense-tracker-1010',
    authDomain: 'expense-tracker-1010.firebaseapp.com',
    storageBucket: 'expense-tracker-1010.firebasestorage.app',
  );
}
